### ISSUE TITLE
iPhone Touch Event

### ISSUE THREAD

**Issue by bryananthonylewis** [ascott1/bigSlide.js#14]
I've been trying to add a .menu-link inside of my .panel which is working fine on Desktop. I have a link in my content area to open the panel and a link inside of the panel to close it. The thought behind this was to create a "X" in the upper left hand side of the panel to close the menu .panel 

As stated above, the .menu-link works fine on the Desktop to close the .panel but when I click the link on my iPhone to close the .panel it does not work. 

When I remove the following from the script from the JS the .menu-link seems to work fine again. 

   menuLink.on('touchend', function(e){
      menuLink.trigger('click.bigSlide');
      e.preventDefault();
    });

Thoughts on this?

UPDATE: I tried using e.stopImmediatePropagation(); instead of e.preventDefault(); and it's working fine too.

**Comment by lentilz** [comment]
I am still having issues with the menu opening specifically on iOS, on both v0.6 and 0.7. Ive got it to work for iOS by using both
e.preventDefault();
e.stopImmediatePropagation();

..on the click and touch event listeners but its laggy compared to other devices.

**Comment by ascott1** [comment]
@lentilz is it laggy for you on the demo page <http://ascott1.github.io/bigSlide.js/>?

**Comment by lentilz** [comment]
Nope, working fine on the demo page. Will give using fastclick a go and see if that resolves this case.

**Comment by ascott1** [comment]
Hmm, if it's working on the demo page then it must be a problem with either some markup on the page or a conflicting script.
