### ISSUE TITLE
click anywhere to close slide

### ISSUE THREAD

**Issue by Lismont** [ascott1/bigSlide.js#17]
Hello,

Would it not be interesting for this (very good!) slide to implement a «click anywhere of the page to close the slide» function? I tried but didn't manage to do it.

Thanks!
Jonas

**Comment by rubaff** [comment]
Heres the code I'm using:

    $("a#someexternallink").click(function() {
         $(".nav-toggle .nav").trigger("click");
    });

**Comment by ascott1** [comment]
This is actually available as a native feature now by setting the `easyClose` option to `true`. My apologies for not posting that here.
