### ISSUE TITLE
2 instance of big slide doesn't seems to work

### ISSUE THREAD

**Issue by jdehaas** [ascott1/bigSlide.js#18]
Hi,

I am using bigSlide for one of my project on mobile. I have one left menu and one right menu triggered by to links:

```
$('#a_list').bigSlide({
    menu: '#menu',
    side:'left'
});
$('#a_option').bigSlide({
    menu: '#option_menu',
    side:'right'
});
```

The second one is not working. When I remove the first one, the second one is working... Can't we have 2 instance of bigSlide() ?

Many thanks

**Comment by sankbhatt** [comment]
Hi,

i am trying use the same code for having two BigSlides on one page, but not sure where i am missing
here is the code http://sanketbhatt.com/ecom/
all i want is that when i click on hamburger menu the BigSlide should come from left (which thankfully is working fine) and when i click on cart the BigSlide should come from right, which is not working
i have used the side: 'right' option to do so here http://sanketbhatt.com/ecom/index1.html

**Comment by kogcyc** [comment]
Hi.

I used @camilonova 's suggestion and implemented an example which is running on jsfiddle here:

https://jsfiddle.net/kogcyc/qwg1xu28/

Hope someone finds it useful.

Thanks to all!
