### ISSUE TITLE
Overflow-x

### ISSUE THREAD

**Issue by asacarter** [ascott1/bigSlide.js#26]
You also need to add overflow-x to body and html otherwise the main content can be swiped under the nav.

Maybe this can be added the dom when the panel is open?

I just add it to my style sheet in a mobile media query though..

**Comment by aastudio** [comment]
Did you had time to add it ?

**Comment by ascott1** [comment]
No, I haven't added this to the documentation as it appears to be situational. The demo site, for example, does not require `overflow-x` to the body or html: http://ascott1.github.io/bigSlide.js/.

Let me know if there's something I'm missing here!
