### ISSUE TITLE
Cleanup bower package

### ISSUE THREAD

**Issue by camilonova** [ascott1/bigSlide.js#30]
I've installed the package using bower and then is not clear which file should I use:

![main_js](https://cloud.githubusercontent.com/assets/202559/4242951/70eb558e-3a04-11e4-8ee6-13b3d0838841.png)

Usually all libraries use **dist** folder, so I started using the file ```bigSlide.min.js``` but it doesn't work as expected, then I tried ```jquery.big-slide.js``` and that one is more recently updated than the other one, I think thats the one you want people to use.

Should be great if you put into the **src** folder one file called ```jquery.bigSlide.js``` and then in **dist** folder put one file ```jquery.bigSlide.min.js``` so you can avoid confusion to users trying to use the library.

Maybe you have this layout because of the demo, but you can easily update it to match this new layout.

Thanks.

**Comment by ascott1** [comment]
Fixed! Going to add some contributing guidelines in the near future so that this doesn't happen again.
