### ISSUE TITLE
Right menu is not pushing content

### ISSUE THREAD

**Issue by camilonova** [ascott1/bigSlide.js#31]
Look at this: http://codepen.io/anon/pen/lBhbC

There you can see the right menu is not pushing the container, I think it is because you set the css rule ```left: 0``` and you should set ```left: auto```. Can you take a look to fix it?

**Comment by ascott1** [comment]
Closing this issue as I don't have the intention of implementing menus on both sides. There may be other  larger plugins that allow this.
