### ISSUE TITLE
Closing automatically on click of Slide

### ISSUE THREAD

**Issue by nunomen** [ascott1/bigSlide.js#36]
When menu is open, clicking anywhere on the slide will automatiicaly close the slide. Is there a way to prevent this? This does't seem to be an issue on the official BigSlide website demo, however in the downloaded demo it behaves this way.

Also, is there a way to disable automatically close of slide when clicking on pushed content similar to the official website?

Cheers

**Comment by ascott1** [comment]
This has been fixed in 0.6.0.
