### ISSUE TITLE
iOS Seems buggy at best

### ISSUE THREAD

**Issue by nate8684** [ascott1/bigSlide.js#38]
I installed this and it works flawlessly in a desktop browser. As soon as I try it on my iPhone 6+ it was was very particular on where I pressed in order to make it work. Clicking directly nudges things 1px and then back again. If I click on the very edge of the button it seems to mostly work. I thought this might be just something I did wrong, however looking at the plugin site yields the same results. Is anyone else having this issue and figured out how to solve it? Is this something I have to get use to on mobile devices? Let me know, thanks!

**Comment by ascott1** [comment]
Hey @nate8684 check out the latest version (0.6.0). It seems to be working pretty well on my iPhone 6. Let me know if you are still having issues on the 6+.

**Comment by nate8684** [comment]
That's much better, should've tried that before posting an issue. Thanks for the heads, great plugin!

**Comment by ascott1** [comment]
:+1: excellent!
