### ISSUE TITLE
Disable scroll/swipe on pushed content

### ISSUE THREAD

**Issue by earthsky** [ascott1/bigSlide.js#4]
First, love the plugin. Lightweight and quick to integrate. 

One thing that I was hoping to do is disable scroll/swipe on the pushed content; fix its position, in other words. Any thoughts on how to best achieve this with CSS, or is this something you can roll into the plugin?

Cheers, and keep up the great work.

**Comment by olivezz** [comment]
You don't have to write external code, just write it in 'afterOpen' settings
'afterOpen': function() { $( "body" ).css( "overflow-y", "hidden" );
