### ISSUE TITLE
menu on open white gap 

### ISSUE THREAD

**Issue by stigk** [ascott1/bigSlide.js#41]
When menu is opened for the first time on page load i get a gap between the menu and warp div showing the body color in the gap. 

If i close the menu and open it  again the gap will not appear until i refresh the page and open menu.

Anyway to fix this?

**Comment by ascott1** [comment]
@stigk do you have a link to the code? Is this happening for you at http://ascott1.github.io/bigSlide.js/? 

Thanks!

**Comment by stigk** [comment]
@ascott1 No, it is not happening for me on  http://ascott1.github.io/bigSlide.js/ 

Here is my [Link ](http://mcubesolutions.co.in/sdnabeta/)

Thanks for the quick reply, really like this plugin.

**Comment by ascott1** [comment]
Thanks!

I took a look at the site and I can't see what's causing it immediately. It looks like you have a `.warp` class that contains everything that gets pushed, but each individual element id is given 'position: relative'. Maybe try applying that to the class to make sure nothing is missed? It seems to be an odd delay between the container transitioning and the menu transitioning.

Sorry I'm not of much help! Hopefully that gets you pointed in the right direction.

**Comment by stigk** [comment]
Hey, thanks for getting back.

I figured it out there were few typos .warp and .wrap my own fault not noticing it, the delay was from the width some how the width i had was causing it.changed it to lower width now it is working brilliantly smooth.

Thanks.

**Comment by ascott1** [comment]
Glad to hear it!
