### ISSUE TITLE
Can't get the page to slide out with nav.

### ISSUE THREAD

**Issue by antistandard** [ascott1/bigSlide.js#47]
Hi,

I can get the nav working and I love how light-weight and smooth this is, however, I can't get my main content page div to slide out as well when the nav slides out.

Currently the nav just slides out over the top of the page. I want the page to also slide right with the div like the main example on the bigSlide site.

I also have a problem with an img that is contained below the page div that I am trying to slide right with the nav. It's going crazy massive when I apply the position:relative to the page div I am trying to slide right with the nav.

I have my page set up like this:
```
<container class="wrap push">
<nav>...</nav>
<hamburger button>...</button>
</container>
```
All the correct code is in place because the nav works perfectly except that the container doesn't move right with the nav.

Hope I explained this ok.

Thank you for any help.

**Comment by ascott1** [comment]
@antistandard does the container div have the style:

```css
.wrap {
    position: relative;
}
```

If not, try adding that and giving it a shot. I hope that helps!

**Comment by antistandard** [comment]
@ascott1 
Hi, I have added that to my css and that is what is making an image in my code become supersized. I also deleted that image and refreshed browser and tried the nav again but the same thing happened, the page didn't slide out.
There must be some conflicting positioning in my code somewhere. Thanks for your help, I'll try and work it out then I'll let you know how I go.
Thanks

**Comment by ascott1** [comment]
Best of luck @antistandard!
