### ISSUE TITLE
version is still 0.9.1 in the 0.9.2 dist files

### ISSUE THREAD

**Issue by szexigexi** [ascott1/bigSlide.js#58]
hi,

i downloaded the latest release (0.9.2) and in the dist files the version is still 0.9.1. it's not a huge problem but maybe something went wrong in the build. i did not have time to check it out just wanted to notify you. :)

**Comment by ascott1** [comment]
Thanks for the heads up @szexigexi! I'll fix this asap and close this issue when done.

**Comment by ascott1** [comment]
This is done. I bumped it to 0.9.3 as it's likely that the 0.9.1 dist files were published as part of the 0.9.2 release.

Thanks again!
