### ISSUE TITLE
A couple possible improvements. Remain state and semi-open state

### ISSUE THREAD

**Issue by joanvila** [ascott1/bigSlide.js#64]
I am very happy using this plugin on my websites but I I miss a couple functionalities.

The first one and related to the issue [#23](https://github.com/ascott1/bigSlide.js/issues/23) I would like to choose if the menu is opened by default depending on the scree size. I would also have an option to store in local storage if the user had the menu opened or closed so when changing the page, the menu could remain opened.

The second one is that I think it would be very nice to have a semi-open state in which only the icons or a part of each menu entry would be shown. Without the text or the second part. This way, on low resolution devices, the menu could be visible anytime because it would be thin.

If you don't mind, I can try to code it with a pull request.

Happy coding!

**Comment by ascott1** [comment]
These are great suggestions @joanvila and I would certainly welcome any pull requests!

**Comment by joanvila** [comment]
It's done now :)

**Comment by ascott1** [comment]
:tada: Thanks for this great work @joanvila!
