### ISSUE TITLE
Implementing bigSlide.js into Magento

### ISSUE THREAD

**Issue by Monis247** [ascott1/bigSlide.js#79]
Followed all steps jQuery does not seem to be triggering at all. Any advise would be appriciated!

**Comment by ascott1** [comment]
Hi @Monis247 is jQuery itself being loaded by the page?

**Comment by Monis247** [comment]
Apologies, used the bit of code below and worked a treat!

var $j = jQuery.noConflict(); 

    $j(document).ready(function() {
        $j('.menu-link').bigSlide();
    });

**Comment by ascott1** [comment]
Great!
