### ISSUE TITLE
Preventing Vertical Scrollbar on Browser

### ISSUE THREAD

**Issue by robertallenbaker** [ascott1/bigSlide.js#82]
Hi Adam,

First off, thank you so much for this application!  It's quick and easy to apply.  I implemented it on my site, but unlike your demo mine came up with a vertical scrollbar at the bottom.  How did you combat this?  Was it just as simple as an overflow-x on the html,body tag?

**Comment by ascott1** [comment]
Thanks @robertallenbaker!

Do you have `position: relative` set on your container class? See https://github.com/ascott1/bigSlide.js/blob/master/demo/css/simple.css#L24 for an example.
