### ISSUE TITLE
Typo in "Getting Started" code.

### ISSUE THREAD

**Issue by husteadrobert** [ascott1/bigSlide.js#94]
In the final section of "Getting Started" where you give an example of passing options to bigSlide, there is a typo in the example code.

```
<script>
$(document).ready(function() {
    $('.menu-link').bigSlide({
	menuWidth:'18em',
	push:'(.mypush)',
	speed:'450'
});
});
</script>
```

The `push:'(.mypush)',` line should actually read, `push:('.mypush'),` , with the single quotation marks inside the parenthesis.

**Comment by ascott1** [comment]
Good catch @husteadrobert! Thank you
